# Основные настройки запуска
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

# Настройки вывода
output:
  formats:
    - format: colored-line-number
  print-issued-lines: true
  print-linter-name: true

# Настройки линтеров
linters-settings:
  govet:
    enable:
      - shadow
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

# Включенные линтеры
linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused

# Исключения
issues:
  exclude-use-default: false
  exclude:
    - G104 # Игнорировать _ вместо err
    - "exported func .* returns unexported type .*"
    - "should have a package comment"
    - "don't use an underscore in package name"
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
    - path: \.pb\.go$
    - path: \.pb\.gw\.go$