run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  exclude:
    - "bin/.*"
    - "vendor/.*"
    - "var/.*"
    - "tmp/.*"
    - ".cache/.*"
    - ".*\\.pb\\.go"
    - ".*\\.pb\\.gw\\.go"

output:
  formats:
    - checkstyle
    - json

linters-settings:
  govet: {}
  errcheck: {}

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - unused

issues:
  exclude:
    - "G104" # проверка на errcheck
    - "exported func .* returns unexported type .*"
    - "should have a package comment"
    - "don't use an underscore in package name"
