# More info on config here: https://golangci-lint.run/usage/configuration/#config-file
run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  # Удалена секция issues, так как она вызывает ошибку
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - .cache

output:
  formats:
    - colored-line-number  # Теперь это массив
  print-issued-lines: true
  print-linter-name: true

linters-settings:
  govet:
    # Убрана настройка shadow, которая вызывает ошибку
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused

issues:
  exclude-use-default: false
  exclude:
    - G104 # _ instead of err checks
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
