version: "2"  # Версия конфигурации

run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true

output:
  formats:
    checkstyle:
      path: 'report.xml'  # Путь для отчета в формате Checkstyle
    json:
      path: stdout  # Путь для вывода в формате JSON

linters:
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - unused
  disable: []  # Линтеры, которые нужно выключить

linters-settings:
  govet:
    check-shadowing: true  # Включаем проверку на переопределение переменных
  dupl:
    threshold: 100  # Порог для дублирующихся кусков кода
  goconst:
    min-len: 2  # Минимальная длина строки, которая может быть вынесена как константа
    min-occurrences: 2  # Минимальное количество повторений строки для вынесения в константу
  errcheck:
    ignore-closed: true  # Игнорируем закрытые каналы при проверке ошибок

issues:
  exclude-use-default: false
  exclude:
    - "G104"  # Ошибки, связанные с игнорированием ошибок в коде
    - "exported func .* returns unexported type .*"  # Ошибка с возвращаемым типом
    - "should have a package comment"  # Ошибка с отсутствием комментария к пакету
    - "don't use an underscore in package name"  # Использование подчеркивания в имени пакета
