// Code generated by http://github.com/gojuno/minimock (v3.4.5). DO NOT EDIT.

package mocks

//go:generate minimock -i github.com/MariaPopova99/microservices/internal/repository.LongShortRepository -o long_short_repository_minimock.go -n LongShortRepositoryMock -p mocks

import (
	"context"
	"sync"
	mm_atomic "sync/atomic"
	mm_time "time"

	"github.com/MariaPopova99/microservices/internal/model"
	"github.com/gojuno/minimock/v3"
)

// LongShortRepositoryMock implements mm_repository.LongShortRepository
type LongShortRepositoryMock struct {
	t          minimock.Tester
	finishOnce sync.Once

	funcCreateNewURL          func(ctx context.Context, shortUrl *model.ShortUrls, longUrl *model.LongUrls) (i1 int64, err error)
	funcCreateNewURLOrigin    string
	inspectFuncCreateNewURL   func(ctx context.Context, shortUrl *model.ShortUrls, longUrl *model.LongUrls)
	afterCreateNewURLCounter  uint64
	beforeCreateNewURLCounter uint64
	CreateNewURLMock          mLongShortRepositoryMockCreateNewURL

	funcGetLong          func(ctx context.Context, shortUrl *model.ShortUrls) (up1 *model.UrlFullInfo, err error)
	funcGetLongOrigin    string
	inspectFuncGetLong   func(ctx context.Context, shortUrl *model.ShortUrls)
	afterGetLongCounter  uint64
	beforeGetLongCounter uint64
	GetLongMock          mLongShortRepositoryMockGetLong

	funcGetShort          func(ctx context.Context, LongUrl *model.LongUrls) (up1 *model.UrlFullInfo, err error)
	funcGetShortOrigin    string
	inspectFuncGetShort   func(ctx context.Context, LongUrl *model.LongUrls)
	afterGetShortCounter  uint64
	beforeGetShortCounter uint64
	GetShortMock          mLongShortRepositoryMockGetShort
}

// NewLongShortRepositoryMock returns a mock for mm_repository.LongShortRepository
func NewLongShortRepositoryMock(t minimock.Tester) *LongShortRepositoryMock {
	m := &LongShortRepositoryMock{t: t}

	if controller, ok := t.(minimock.MockController); ok {
		controller.RegisterMocker(m)
	}

	m.CreateNewURLMock = mLongShortRepositoryMockCreateNewURL{mock: m}
	m.CreateNewURLMock.callArgs = []*LongShortRepositoryMockCreateNewURLParams{}

	m.GetLongMock = mLongShortRepositoryMockGetLong{mock: m}
	m.GetLongMock.callArgs = []*LongShortRepositoryMockGetLongParams{}

	m.GetShortMock = mLongShortRepositoryMockGetShort{mock: m}
	m.GetShortMock.callArgs = []*LongShortRepositoryMockGetShortParams{}

	t.Cleanup(m.MinimockFinish)

	return m
}

type mLongShortRepositoryMockCreateNewURL struct {
	optional           bool
	mock               *LongShortRepositoryMock
	defaultExpectation *LongShortRepositoryMockCreateNewURLExpectation
	expectations       []*LongShortRepositoryMockCreateNewURLExpectation

	callArgs []*LongShortRepositoryMockCreateNewURLParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LongShortRepositoryMockCreateNewURLExpectation specifies expectation struct of the LongShortRepository.CreateNewURL
type LongShortRepositoryMockCreateNewURLExpectation struct {
	mock               *LongShortRepositoryMock
	params             *LongShortRepositoryMockCreateNewURLParams
	paramPtrs          *LongShortRepositoryMockCreateNewURLParamPtrs
	expectationOrigins LongShortRepositoryMockCreateNewURLExpectationOrigins
	results            *LongShortRepositoryMockCreateNewURLResults
	returnOrigin       string
	Counter            uint64
}

// LongShortRepositoryMockCreateNewURLParams contains parameters of the LongShortRepository.CreateNewURL
type LongShortRepositoryMockCreateNewURLParams struct {
	ctx      context.Context
	shortUrl *model.ShortUrls
	longUrl  *model.LongUrls
}

// LongShortRepositoryMockCreateNewURLParamPtrs contains pointers to parameters of the LongShortRepository.CreateNewURL
type LongShortRepositoryMockCreateNewURLParamPtrs struct {
	ctx      *context.Context
	shortUrl **model.ShortUrls
	longUrl  **model.LongUrls
}

// LongShortRepositoryMockCreateNewURLResults contains results of the LongShortRepository.CreateNewURL
type LongShortRepositoryMockCreateNewURLResults struct {
	i1  int64
	err error
}

// LongShortRepositoryMockCreateNewURLOrigins contains origins of expectations of the LongShortRepository.CreateNewURL
type LongShortRepositoryMockCreateNewURLExpectationOrigins struct {
	origin         string
	originCtx      string
	originShortUrl string
	originLongUrl  string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) Optional() *mLongShortRepositoryMockCreateNewURL {
	mmCreateNewURL.optional = true
	return mmCreateNewURL
}

// Expect sets up expected params for LongShortRepository.CreateNewURL
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) Expect(ctx context.Context, shortUrl *model.ShortUrls, longUrl *model.LongUrls) *mLongShortRepositoryMockCreateNewURL {
	if mmCreateNewURL.mock.funcCreateNewURL != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Set")
	}

	if mmCreateNewURL.defaultExpectation == nil {
		mmCreateNewURL.defaultExpectation = &LongShortRepositoryMockCreateNewURLExpectation{}
	}

	if mmCreateNewURL.defaultExpectation.paramPtrs != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by ExpectParams functions")
	}

	mmCreateNewURL.defaultExpectation.params = &LongShortRepositoryMockCreateNewURLParams{ctx, shortUrl, longUrl}
	mmCreateNewURL.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmCreateNewURL.expectations {
		if minimock.Equal(e.params, mmCreateNewURL.defaultExpectation.params) {
			mmCreateNewURL.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmCreateNewURL.defaultExpectation.params)
		}
	}

	return mmCreateNewURL
}

// ExpectCtxParam1 sets up expected param ctx for LongShortRepository.CreateNewURL
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) ExpectCtxParam1(ctx context.Context) *mLongShortRepositoryMockCreateNewURL {
	if mmCreateNewURL.mock.funcCreateNewURL != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Set")
	}

	if mmCreateNewURL.defaultExpectation == nil {
		mmCreateNewURL.defaultExpectation = &LongShortRepositoryMockCreateNewURLExpectation{}
	}

	if mmCreateNewURL.defaultExpectation.params != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Expect")
	}

	if mmCreateNewURL.defaultExpectation.paramPtrs == nil {
		mmCreateNewURL.defaultExpectation.paramPtrs = &LongShortRepositoryMockCreateNewURLParamPtrs{}
	}
	mmCreateNewURL.defaultExpectation.paramPtrs.ctx = &ctx
	mmCreateNewURL.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmCreateNewURL
}

// ExpectShortUrlParam2 sets up expected param shortUrl for LongShortRepository.CreateNewURL
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) ExpectShortUrlParam2(shortUrl *model.ShortUrls) *mLongShortRepositoryMockCreateNewURL {
	if mmCreateNewURL.mock.funcCreateNewURL != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Set")
	}

	if mmCreateNewURL.defaultExpectation == nil {
		mmCreateNewURL.defaultExpectation = &LongShortRepositoryMockCreateNewURLExpectation{}
	}

	if mmCreateNewURL.defaultExpectation.params != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Expect")
	}

	if mmCreateNewURL.defaultExpectation.paramPtrs == nil {
		mmCreateNewURL.defaultExpectation.paramPtrs = &LongShortRepositoryMockCreateNewURLParamPtrs{}
	}
	mmCreateNewURL.defaultExpectation.paramPtrs.shortUrl = &shortUrl
	mmCreateNewURL.defaultExpectation.expectationOrigins.originShortUrl = minimock.CallerInfo(1)

	return mmCreateNewURL
}

// ExpectLongUrlParam3 sets up expected param longUrl for LongShortRepository.CreateNewURL
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) ExpectLongUrlParam3(longUrl *model.LongUrls) *mLongShortRepositoryMockCreateNewURL {
	if mmCreateNewURL.mock.funcCreateNewURL != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Set")
	}

	if mmCreateNewURL.defaultExpectation == nil {
		mmCreateNewURL.defaultExpectation = &LongShortRepositoryMockCreateNewURLExpectation{}
	}

	if mmCreateNewURL.defaultExpectation.params != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Expect")
	}

	if mmCreateNewURL.defaultExpectation.paramPtrs == nil {
		mmCreateNewURL.defaultExpectation.paramPtrs = &LongShortRepositoryMockCreateNewURLParamPtrs{}
	}
	mmCreateNewURL.defaultExpectation.paramPtrs.longUrl = &longUrl
	mmCreateNewURL.defaultExpectation.expectationOrigins.originLongUrl = minimock.CallerInfo(1)

	return mmCreateNewURL
}

// Inspect accepts an inspector function that has same arguments as the LongShortRepository.CreateNewURL
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) Inspect(f func(ctx context.Context, shortUrl *model.ShortUrls, longUrl *model.LongUrls)) *mLongShortRepositoryMockCreateNewURL {
	if mmCreateNewURL.mock.inspectFuncCreateNewURL != nil {
		mmCreateNewURL.mock.t.Fatalf("Inspect function is already set for LongShortRepositoryMock.CreateNewURL")
	}

	mmCreateNewURL.mock.inspectFuncCreateNewURL = f

	return mmCreateNewURL
}

// Return sets up results that will be returned by LongShortRepository.CreateNewURL
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) Return(i1 int64, err error) *LongShortRepositoryMock {
	if mmCreateNewURL.mock.funcCreateNewURL != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Set")
	}

	if mmCreateNewURL.defaultExpectation == nil {
		mmCreateNewURL.defaultExpectation = &LongShortRepositoryMockCreateNewURLExpectation{mock: mmCreateNewURL.mock}
	}
	mmCreateNewURL.defaultExpectation.results = &LongShortRepositoryMockCreateNewURLResults{i1, err}
	mmCreateNewURL.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmCreateNewURL.mock
}

// Set uses given function f to mock the LongShortRepository.CreateNewURL method
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) Set(f func(ctx context.Context, shortUrl *model.ShortUrls, longUrl *model.LongUrls) (i1 int64, err error)) *LongShortRepositoryMock {
	if mmCreateNewURL.defaultExpectation != nil {
		mmCreateNewURL.mock.t.Fatalf("Default expectation is already set for the LongShortRepository.CreateNewURL method")
	}

	if len(mmCreateNewURL.expectations) > 0 {
		mmCreateNewURL.mock.t.Fatalf("Some expectations are already set for the LongShortRepository.CreateNewURL method")
	}

	mmCreateNewURL.mock.funcCreateNewURL = f
	mmCreateNewURL.mock.funcCreateNewURLOrigin = minimock.CallerInfo(1)
	return mmCreateNewURL.mock
}

// When sets expectation for the LongShortRepository.CreateNewURL which will trigger the result defined by the following
// Then helper
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) When(ctx context.Context, shortUrl *model.ShortUrls, longUrl *model.LongUrls) *LongShortRepositoryMockCreateNewURLExpectation {
	if mmCreateNewURL.mock.funcCreateNewURL != nil {
		mmCreateNewURL.mock.t.Fatalf("LongShortRepositoryMock.CreateNewURL mock is already set by Set")
	}

	expectation := &LongShortRepositoryMockCreateNewURLExpectation{
		mock:               mmCreateNewURL.mock,
		params:             &LongShortRepositoryMockCreateNewURLParams{ctx, shortUrl, longUrl},
		expectationOrigins: LongShortRepositoryMockCreateNewURLExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmCreateNewURL.expectations = append(mmCreateNewURL.expectations, expectation)
	return expectation
}

// Then sets up LongShortRepository.CreateNewURL return parameters for the expectation previously defined by the When method
func (e *LongShortRepositoryMockCreateNewURLExpectation) Then(i1 int64, err error) *LongShortRepositoryMock {
	e.results = &LongShortRepositoryMockCreateNewURLResults{i1, err}
	return e.mock
}

// Times sets number of times LongShortRepository.CreateNewURL should be invoked
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) Times(n uint64) *mLongShortRepositoryMockCreateNewURL {
	if n == 0 {
		mmCreateNewURL.mock.t.Fatalf("Times of LongShortRepositoryMock.CreateNewURL mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmCreateNewURL.expectedInvocations, n)
	mmCreateNewURL.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmCreateNewURL
}

func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) invocationsDone() bool {
	if len(mmCreateNewURL.expectations) == 0 && mmCreateNewURL.defaultExpectation == nil && mmCreateNewURL.mock.funcCreateNewURL == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmCreateNewURL.mock.afterCreateNewURLCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmCreateNewURL.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// CreateNewURL implements mm_repository.LongShortRepository
func (mmCreateNewURL *LongShortRepositoryMock) CreateNewURL(ctx context.Context, shortUrl *model.ShortUrls, longUrl *model.LongUrls) (i1 int64, err error) {
	mm_atomic.AddUint64(&mmCreateNewURL.beforeCreateNewURLCounter, 1)
	defer mm_atomic.AddUint64(&mmCreateNewURL.afterCreateNewURLCounter, 1)

	mmCreateNewURL.t.Helper()

	if mmCreateNewURL.inspectFuncCreateNewURL != nil {
		mmCreateNewURL.inspectFuncCreateNewURL(ctx, shortUrl, longUrl)
	}

	mm_params := LongShortRepositoryMockCreateNewURLParams{ctx, shortUrl, longUrl}

	// Record call args
	mmCreateNewURL.CreateNewURLMock.mutex.Lock()
	mmCreateNewURL.CreateNewURLMock.callArgs = append(mmCreateNewURL.CreateNewURLMock.callArgs, &mm_params)
	mmCreateNewURL.CreateNewURLMock.mutex.Unlock()

	for _, e := range mmCreateNewURL.CreateNewURLMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.i1, e.results.err
		}
	}

	if mmCreateNewURL.CreateNewURLMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmCreateNewURL.CreateNewURLMock.defaultExpectation.Counter, 1)
		mm_want := mmCreateNewURL.CreateNewURLMock.defaultExpectation.params
		mm_want_ptrs := mmCreateNewURL.CreateNewURLMock.defaultExpectation.paramPtrs

		mm_got := LongShortRepositoryMockCreateNewURLParams{ctx, shortUrl, longUrl}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmCreateNewURL.t.Errorf("LongShortRepositoryMock.CreateNewURL got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateNewURL.CreateNewURLMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.shortUrl != nil && !minimock.Equal(*mm_want_ptrs.shortUrl, mm_got.shortUrl) {
				mmCreateNewURL.t.Errorf("LongShortRepositoryMock.CreateNewURL got unexpected parameter shortUrl, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateNewURL.CreateNewURLMock.defaultExpectation.expectationOrigins.originShortUrl, *mm_want_ptrs.shortUrl, mm_got.shortUrl, minimock.Diff(*mm_want_ptrs.shortUrl, mm_got.shortUrl))
			}

			if mm_want_ptrs.longUrl != nil && !minimock.Equal(*mm_want_ptrs.longUrl, mm_got.longUrl) {
				mmCreateNewURL.t.Errorf("LongShortRepositoryMock.CreateNewURL got unexpected parameter longUrl, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmCreateNewURL.CreateNewURLMock.defaultExpectation.expectationOrigins.originLongUrl, *mm_want_ptrs.longUrl, mm_got.longUrl, minimock.Diff(*mm_want_ptrs.longUrl, mm_got.longUrl))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmCreateNewURL.t.Errorf("LongShortRepositoryMock.CreateNewURL got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmCreateNewURL.CreateNewURLMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmCreateNewURL.CreateNewURLMock.defaultExpectation.results
		if mm_results == nil {
			mmCreateNewURL.t.Fatal("No results are set for the LongShortRepositoryMock.CreateNewURL")
		}
		return (*mm_results).i1, (*mm_results).err
	}
	if mmCreateNewURL.funcCreateNewURL != nil {
		return mmCreateNewURL.funcCreateNewURL(ctx, shortUrl, longUrl)
	}
	mmCreateNewURL.t.Fatalf("Unexpected call to LongShortRepositoryMock.CreateNewURL. %v %v %v", ctx, shortUrl, longUrl)
	return
}

// CreateNewURLAfterCounter returns a count of finished LongShortRepositoryMock.CreateNewURL invocations
func (mmCreateNewURL *LongShortRepositoryMock) CreateNewURLAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateNewURL.afterCreateNewURLCounter)
}

// CreateNewURLBeforeCounter returns a count of LongShortRepositoryMock.CreateNewURL invocations
func (mmCreateNewURL *LongShortRepositoryMock) CreateNewURLBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmCreateNewURL.beforeCreateNewURLCounter)
}

// Calls returns a list of arguments used in each call to LongShortRepositoryMock.CreateNewURL.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmCreateNewURL *mLongShortRepositoryMockCreateNewURL) Calls() []*LongShortRepositoryMockCreateNewURLParams {
	mmCreateNewURL.mutex.RLock()

	argCopy := make([]*LongShortRepositoryMockCreateNewURLParams, len(mmCreateNewURL.callArgs))
	copy(argCopy, mmCreateNewURL.callArgs)

	mmCreateNewURL.mutex.RUnlock()

	return argCopy
}

// MinimockCreateNewURLDone returns true if the count of the CreateNewURL invocations corresponds
// the number of defined expectations
func (m *LongShortRepositoryMock) MinimockCreateNewURLDone() bool {
	if m.CreateNewURLMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.CreateNewURLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.CreateNewURLMock.invocationsDone()
}

// MinimockCreateNewURLInspect logs each unmet expectation
func (m *LongShortRepositoryMock) MinimockCreateNewURLInspect() {
	for _, e := range m.CreateNewURLMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LongShortRepositoryMock.CreateNewURL at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterCreateNewURLCounter := mm_atomic.LoadUint64(&m.afterCreateNewURLCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.CreateNewURLMock.defaultExpectation != nil && afterCreateNewURLCounter < 1 {
		if m.CreateNewURLMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LongShortRepositoryMock.CreateNewURL at\n%s", m.CreateNewURLMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LongShortRepositoryMock.CreateNewURL at\n%s with params: %#v", m.CreateNewURLMock.defaultExpectation.expectationOrigins.origin, *m.CreateNewURLMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcCreateNewURL != nil && afterCreateNewURLCounter < 1 {
		m.t.Errorf("Expected call to LongShortRepositoryMock.CreateNewURL at\n%s", m.funcCreateNewURLOrigin)
	}

	if !m.CreateNewURLMock.invocationsDone() && afterCreateNewURLCounter > 0 {
		m.t.Errorf("Expected %d calls to LongShortRepositoryMock.CreateNewURL at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.CreateNewURLMock.expectedInvocations), m.CreateNewURLMock.expectedInvocationsOrigin, afterCreateNewURLCounter)
	}
}

type mLongShortRepositoryMockGetLong struct {
	optional           bool
	mock               *LongShortRepositoryMock
	defaultExpectation *LongShortRepositoryMockGetLongExpectation
	expectations       []*LongShortRepositoryMockGetLongExpectation

	callArgs []*LongShortRepositoryMockGetLongParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LongShortRepositoryMockGetLongExpectation specifies expectation struct of the LongShortRepository.GetLong
type LongShortRepositoryMockGetLongExpectation struct {
	mock               *LongShortRepositoryMock
	params             *LongShortRepositoryMockGetLongParams
	paramPtrs          *LongShortRepositoryMockGetLongParamPtrs
	expectationOrigins LongShortRepositoryMockGetLongExpectationOrigins
	results            *LongShortRepositoryMockGetLongResults
	returnOrigin       string
	Counter            uint64
}

// LongShortRepositoryMockGetLongParams contains parameters of the LongShortRepository.GetLong
type LongShortRepositoryMockGetLongParams struct {
	ctx      context.Context
	shortUrl *model.ShortUrls
}

// LongShortRepositoryMockGetLongParamPtrs contains pointers to parameters of the LongShortRepository.GetLong
type LongShortRepositoryMockGetLongParamPtrs struct {
	ctx      *context.Context
	shortUrl **model.ShortUrls
}

// LongShortRepositoryMockGetLongResults contains results of the LongShortRepository.GetLong
type LongShortRepositoryMockGetLongResults struct {
	up1 *model.UrlFullInfo
	err error
}

// LongShortRepositoryMockGetLongOrigins contains origins of expectations of the LongShortRepository.GetLong
type LongShortRepositoryMockGetLongExpectationOrigins struct {
	origin         string
	originCtx      string
	originShortUrl string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetLong *mLongShortRepositoryMockGetLong) Optional() *mLongShortRepositoryMockGetLong {
	mmGetLong.optional = true
	return mmGetLong
}

// Expect sets up expected params for LongShortRepository.GetLong
func (mmGetLong *mLongShortRepositoryMockGetLong) Expect(ctx context.Context, shortUrl *model.ShortUrls) *mLongShortRepositoryMockGetLong {
	if mmGetLong.mock.funcGetLong != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by Set")
	}

	if mmGetLong.defaultExpectation == nil {
		mmGetLong.defaultExpectation = &LongShortRepositoryMockGetLongExpectation{}
	}

	if mmGetLong.defaultExpectation.paramPtrs != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by ExpectParams functions")
	}

	mmGetLong.defaultExpectation.params = &LongShortRepositoryMockGetLongParams{ctx, shortUrl}
	mmGetLong.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetLong.expectations {
		if minimock.Equal(e.params, mmGetLong.defaultExpectation.params) {
			mmGetLong.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetLong.defaultExpectation.params)
		}
	}

	return mmGetLong
}

// ExpectCtxParam1 sets up expected param ctx for LongShortRepository.GetLong
func (mmGetLong *mLongShortRepositoryMockGetLong) ExpectCtxParam1(ctx context.Context) *mLongShortRepositoryMockGetLong {
	if mmGetLong.mock.funcGetLong != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by Set")
	}

	if mmGetLong.defaultExpectation == nil {
		mmGetLong.defaultExpectation = &LongShortRepositoryMockGetLongExpectation{}
	}

	if mmGetLong.defaultExpectation.params != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by Expect")
	}

	if mmGetLong.defaultExpectation.paramPtrs == nil {
		mmGetLong.defaultExpectation.paramPtrs = &LongShortRepositoryMockGetLongParamPtrs{}
	}
	mmGetLong.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetLong.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetLong
}

// ExpectShortUrlParam2 sets up expected param shortUrl for LongShortRepository.GetLong
func (mmGetLong *mLongShortRepositoryMockGetLong) ExpectShortUrlParam2(shortUrl *model.ShortUrls) *mLongShortRepositoryMockGetLong {
	if mmGetLong.mock.funcGetLong != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by Set")
	}

	if mmGetLong.defaultExpectation == nil {
		mmGetLong.defaultExpectation = &LongShortRepositoryMockGetLongExpectation{}
	}

	if mmGetLong.defaultExpectation.params != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by Expect")
	}

	if mmGetLong.defaultExpectation.paramPtrs == nil {
		mmGetLong.defaultExpectation.paramPtrs = &LongShortRepositoryMockGetLongParamPtrs{}
	}
	mmGetLong.defaultExpectation.paramPtrs.shortUrl = &shortUrl
	mmGetLong.defaultExpectation.expectationOrigins.originShortUrl = minimock.CallerInfo(1)

	return mmGetLong
}

// Inspect accepts an inspector function that has same arguments as the LongShortRepository.GetLong
func (mmGetLong *mLongShortRepositoryMockGetLong) Inspect(f func(ctx context.Context, shortUrl *model.ShortUrls)) *mLongShortRepositoryMockGetLong {
	if mmGetLong.mock.inspectFuncGetLong != nil {
		mmGetLong.mock.t.Fatalf("Inspect function is already set for LongShortRepositoryMock.GetLong")
	}

	mmGetLong.mock.inspectFuncGetLong = f

	return mmGetLong
}

// Return sets up results that will be returned by LongShortRepository.GetLong
func (mmGetLong *mLongShortRepositoryMockGetLong) Return(up1 *model.UrlFullInfo, err error) *LongShortRepositoryMock {
	if mmGetLong.mock.funcGetLong != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by Set")
	}

	if mmGetLong.defaultExpectation == nil {
		mmGetLong.defaultExpectation = &LongShortRepositoryMockGetLongExpectation{mock: mmGetLong.mock}
	}
	mmGetLong.defaultExpectation.results = &LongShortRepositoryMockGetLongResults{up1, err}
	mmGetLong.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetLong.mock
}

// Set uses given function f to mock the LongShortRepository.GetLong method
func (mmGetLong *mLongShortRepositoryMockGetLong) Set(f func(ctx context.Context, shortUrl *model.ShortUrls) (up1 *model.UrlFullInfo, err error)) *LongShortRepositoryMock {
	if mmGetLong.defaultExpectation != nil {
		mmGetLong.mock.t.Fatalf("Default expectation is already set for the LongShortRepository.GetLong method")
	}

	if len(mmGetLong.expectations) > 0 {
		mmGetLong.mock.t.Fatalf("Some expectations are already set for the LongShortRepository.GetLong method")
	}

	mmGetLong.mock.funcGetLong = f
	mmGetLong.mock.funcGetLongOrigin = minimock.CallerInfo(1)
	return mmGetLong.mock
}

// When sets expectation for the LongShortRepository.GetLong which will trigger the result defined by the following
// Then helper
func (mmGetLong *mLongShortRepositoryMockGetLong) When(ctx context.Context, shortUrl *model.ShortUrls) *LongShortRepositoryMockGetLongExpectation {
	if mmGetLong.mock.funcGetLong != nil {
		mmGetLong.mock.t.Fatalf("LongShortRepositoryMock.GetLong mock is already set by Set")
	}

	expectation := &LongShortRepositoryMockGetLongExpectation{
		mock:               mmGetLong.mock,
		params:             &LongShortRepositoryMockGetLongParams{ctx, shortUrl},
		expectationOrigins: LongShortRepositoryMockGetLongExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetLong.expectations = append(mmGetLong.expectations, expectation)
	return expectation
}

// Then sets up LongShortRepository.GetLong return parameters for the expectation previously defined by the When method
func (e *LongShortRepositoryMockGetLongExpectation) Then(up1 *model.UrlFullInfo, err error) *LongShortRepositoryMock {
	e.results = &LongShortRepositoryMockGetLongResults{up1, err}
	return e.mock
}

// Times sets number of times LongShortRepository.GetLong should be invoked
func (mmGetLong *mLongShortRepositoryMockGetLong) Times(n uint64) *mLongShortRepositoryMockGetLong {
	if n == 0 {
		mmGetLong.mock.t.Fatalf("Times of LongShortRepositoryMock.GetLong mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetLong.expectedInvocations, n)
	mmGetLong.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetLong
}

func (mmGetLong *mLongShortRepositoryMockGetLong) invocationsDone() bool {
	if len(mmGetLong.expectations) == 0 && mmGetLong.defaultExpectation == nil && mmGetLong.mock.funcGetLong == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetLong.mock.afterGetLongCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetLong.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetLong implements mm_repository.LongShortRepository
func (mmGetLong *LongShortRepositoryMock) GetLong(ctx context.Context, shortUrl *model.ShortUrls) (up1 *model.UrlFullInfo, err error) {
	mm_atomic.AddUint64(&mmGetLong.beforeGetLongCounter, 1)
	defer mm_atomic.AddUint64(&mmGetLong.afterGetLongCounter, 1)

	mmGetLong.t.Helper()

	if mmGetLong.inspectFuncGetLong != nil {
		mmGetLong.inspectFuncGetLong(ctx, shortUrl)
	}

	mm_params := LongShortRepositoryMockGetLongParams{ctx, shortUrl}

	// Record call args
	mmGetLong.GetLongMock.mutex.Lock()
	mmGetLong.GetLongMock.callArgs = append(mmGetLong.GetLongMock.callArgs, &mm_params)
	mmGetLong.GetLongMock.mutex.Unlock()

	for _, e := range mmGetLong.GetLongMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetLong.GetLongMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetLong.GetLongMock.defaultExpectation.Counter, 1)
		mm_want := mmGetLong.GetLongMock.defaultExpectation.params
		mm_want_ptrs := mmGetLong.GetLongMock.defaultExpectation.paramPtrs

		mm_got := LongShortRepositoryMockGetLongParams{ctx, shortUrl}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetLong.t.Errorf("LongShortRepositoryMock.GetLong got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLong.GetLongMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.shortUrl != nil && !minimock.Equal(*mm_want_ptrs.shortUrl, mm_got.shortUrl) {
				mmGetLong.t.Errorf("LongShortRepositoryMock.GetLong got unexpected parameter shortUrl, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetLong.GetLongMock.defaultExpectation.expectationOrigins.originShortUrl, *mm_want_ptrs.shortUrl, mm_got.shortUrl, minimock.Diff(*mm_want_ptrs.shortUrl, mm_got.shortUrl))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetLong.t.Errorf("LongShortRepositoryMock.GetLong got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetLong.GetLongMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetLong.GetLongMock.defaultExpectation.results
		if mm_results == nil {
			mmGetLong.t.Fatal("No results are set for the LongShortRepositoryMock.GetLong")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetLong.funcGetLong != nil {
		return mmGetLong.funcGetLong(ctx, shortUrl)
	}
	mmGetLong.t.Fatalf("Unexpected call to LongShortRepositoryMock.GetLong. %v %v", ctx, shortUrl)
	return
}

// GetLongAfterCounter returns a count of finished LongShortRepositoryMock.GetLong invocations
func (mmGetLong *LongShortRepositoryMock) GetLongAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLong.afterGetLongCounter)
}

// GetLongBeforeCounter returns a count of LongShortRepositoryMock.GetLong invocations
func (mmGetLong *LongShortRepositoryMock) GetLongBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetLong.beforeGetLongCounter)
}

// Calls returns a list of arguments used in each call to LongShortRepositoryMock.GetLong.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetLong *mLongShortRepositoryMockGetLong) Calls() []*LongShortRepositoryMockGetLongParams {
	mmGetLong.mutex.RLock()

	argCopy := make([]*LongShortRepositoryMockGetLongParams, len(mmGetLong.callArgs))
	copy(argCopy, mmGetLong.callArgs)

	mmGetLong.mutex.RUnlock()

	return argCopy
}

// MinimockGetLongDone returns true if the count of the GetLong invocations corresponds
// the number of defined expectations
func (m *LongShortRepositoryMock) MinimockGetLongDone() bool {
	if m.GetLongMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetLongMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetLongMock.invocationsDone()
}

// MinimockGetLongInspect logs each unmet expectation
func (m *LongShortRepositoryMock) MinimockGetLongInspect() {
	for _, e := range m.GetLongMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LongShortRepositoryMock.GetLong at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetLongCounter := mm_atomic.LoadUint64(&m.afterGetLongCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetLongMock.defaultExpectation != nil && afterGetLongCounter < 1 {
		if m.GetLongMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LongShortRepositoryMock.GetLong at\n%s", m.GetLongMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LongShortRepositoryMock.GetLong at\n%s with params: %#v", m.GetLongMock.defaultExpectation.expectationOrigins.origin, *m.GetLongMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetLong != nil && afterGetLongCounter < 1 {
		m.t.Errorf("Expected call to LongShortRepositoryMock.GetLong at\n%s", m.funcGetLongOrigin)
	}

	if !m.GetLongMock.invocationsDone() && afterGetLongCounter > 0 {
		m.t.Errorf("Expected %d calls to LongShortRepositoryMock.GetLong at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetLongMock.expectedInvocations), m.GetLongMock.expectedInvocationsOrigin, afterGetLongCounter)
	}
}

type mLongShortRepositoryMockGetShort struct {
	optional           bool
	mock               *LongShortRepositoryMock
	defaultExpectation *LongShortRepositoryMockGetShortExpectation
	expectations       []*LongShortRepositoryMockGetShortExpectation

	callArgs []*LongShortRepositoryMockGetShortParams
	mutex    sync.RWMutex

	expectedInvocations       uint64
	expectedInvocationsOrigin string
}

// LongShortRepositoryMockGetShortExpectation specifies expectation struct of the LongShortRepository.GetShort
type LongShortRepositoryMockGetShortExpectation struct {
	mock               *LongShortRepositoryMock
	params             *LongShortRepositoryMockGetShortParams
	paramPtrs          *LongShortRepositoryMockGetShortParamPtrs
	expectationOrigins LongShortRepositoryMockGetShortExpectationOrigins
	results            *LongShortRepositoryMockGetShortResults
	returnOrigin       string
	Counter            uint64
}

// LongShortRepositoryMockGetShortParams contains parameters of the LongShortRepository.GetShort
type LongShortRepositoryMockGetShortParams struct {
	ctx     context.Context
	LongUrl *model.LongUrls
}

// LongShortRepositoryMockGetShortParamPtrs contains pointers to parameters of the LongShortRepository.GetShort
type LongShortRepositoryMockGetShortParamPtrs struct {
	ctx     *context.Context
	LongUrl **model.LongUrls
}

// LongShortRepositoryMockGetShortResults contains results of the LongShortRepository.GetShort
type LongShortRepositoryMockGetShortResults struct {
	up1 *model.UrlFullInfo
	err error
}

// LongShortRepositoryMockGetShortOrigins contains origins of expectations of the LongShortRepository.GetShort
type LongShortRepositoryMockGetShortExpectationOrigins struct {
	origin        string
	originCtx     string
	originLongUrl string
}

// Marks this method to be optional. The default behavior of any method with Return() is '1 or more', meaning
// the test will fail minimock's automatic final call check if the mocked method was not called at least once.
// Optional() makes method check to work in '0 or more' mode.
// It is NOT RECOMMENDED to use this option unless you really need it, as default behaviour helps to
// catch the problems when the expected method call is totally skipped during test run.
func (mmGetShort *mLongShortRepositoryMockGetShort) Optional() *mLongShortRepositoryMockGetShort {
	mmGetShort.optional = true
	return mmGetShort
}

// Expect sets up expected params for LongShortRepository.GetShort
func (mmGetShort *mLongShortRepositoryMockGetShort) Expect(ctx context.Context, LongUrl *model.LongUrls) *mLongShortRepositoryMockGetShort {
	if mmGetShort.mock.funcGetShort != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by Set")
	}

	if mmGetShort.defaultExpectation == nil {
		mmGetShort.defaultExpectation = &LongShortRepositoryMockGetShortExpectation{}
	}

	if mmGetShort.defaultExpectation.paramPtrs != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by ExpectParams functions")
	}

	mmGetShort.defaultExpectation.params = &LongShortRepositoryMockGetShortParams{ctx, LongUrl}
	mmGetShort.defaultExpectation.expectationOrigins.origin = minimock.CallerInfo(1)
	for _, e := range mmGetShort.expectations {
		if minimock.Equal(e.params, mmGetShort.defaultExpectation.params) {
			mmGetShort.mock.t.Fatalf("Expectation set by When has same params: %#v", *mmGetShort.defaultExpectation.params)
		}
	}

	return mmGetShort
}

// ExpectCtxParam1 sets up expected param ctx for LongShortRepository.GetShort
func (mmGetShort *mLongShortRepositoryMockGetShort) ExpectCtxParam1(ctx context.Context) *mLongShortRepositoryMockGetShort {
	if mmGetShort.mock.funcGetShort != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by Set")
	}

	if mmGetShort.defaultExpectation == nil {
		mmGetShort.defaultExpectation = &LongShortRepositoryMockGetShortExpectation{}
	}

	if mmGetShort.defaultExpectation.params != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by Expect")
	}

	if mmGetShort.defaultExpectation.paramPtrs == nil {
		mmGetShort.defaultExpectation.paramPtrs = &LongShortRepositoryMockGetShortParamPtrs{}
	}
	mmGetShort.defaultExpectation.paramPtrs.ctx = &ctx
	mmGetShort.defaultExpectation.expectationOrigins.originCtx = minimock.CallerInfo(1)

	return mmGetShort
}

// ExpectLongUrlParam2 sets up expected param LongUrl for LongShortRepository.GetShort
func (mmGetShort *mLongShortRepositoryMockGetShort) ExpectLongUrlParam2(LongUrl *model.LongUrls) *mLongShortRepositoryMockGetShort {
	if mmGetShort.mock.funcGetShort != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by Set")
	}

	if mmGetShort.defaultExpectation == nil {
		mmGetShort.defaultExpectation = &LongShortRepositoryMockGetShortExpectation{}
	}

	if mmGetShort.defaultExpectation.params != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by Expect")
	}

	if mmGetShort.defaultExpectation.paramPtrs == nil {
		mmGetShort.defaultExpectation.paramPtrs = &LongShortRepositoryMockGetShortParamPtrs{}
	}
	mmGetShort.defaultExpectation.paramPtrs.LongUrl = &LongUrl
	mmGetShort.defaultExpectation.expectationOrigins.originLongUrl = minimock.CallerInfo(1)

	return mmGetShort
}

// Inspect accepts an inspector function that has same arguments as the LongShortRepository.GetShort
func (mmGetShort *mLongShortRepositoryMockGetShort) Inspect(f func(ctx context.Context, LongUrl *model.LongUrls)) *mLongShortRepositoryMockGetShort {
	if mmGetShort.mock.inspectFuncGetShort != nil {
		mmGetShort.mock.t.Fatalf("Inspect function is already set for LongShortRepositoryMock.GetShort")
	}

	mmGetShort.mock.inspectFuncGetShort = f

	return mmGetShort
}

// Return sets up results that will be returned by LongShortRepository.GetShort
func (mmGetShort *mLongShortRepositoryMockGetShort) Return(up1 *model.UrlFullInfo, err error) *LongShortRepositoryMock {
	if mmGetShort.mock.funcGetShort != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by Set")
	}

	if mmGetShort.defaultExpectation == nil {
		mmGetShort.defaultExpectation = &LongShortRepositoryMockGetShortExpectation{mock: mmGetShort.mock}
	}
	mmGetShort.defaultExpectation.results = &LongShortRepositoryMockGetShortResults{up1, err}
	mmGetShort.defaultExpectation.returnOrigin = minimock.CallerInfo(1)
	return mmGetShort.mock
}

// Set uses given function f to mock the LongShortRepository.GetShort method
func (mmGetShort *mLongShortRepositoryMockGetShort) Set(f func(ctx context.Context, LongUrl *model.LongUrls) (up1 *model.UrlFullInfo, err error)) *LongShortRepositoryMock {
	if mmGetShort.defaultExpectation != nil {
		mmGetShort.mock.t.Fatalf("Default expectation is already set for the LongShortRepository.GetShort method")
	}

	if len(mmGetShort.expectations) > 0 {
		mmGetShort.mock.t.Fatalf("Some expectations are already set for the LongShortRepository.GetShort method")
	}

	mmGetShort.mock.funcGetShort = f
	mmGetShort.mock.funcGetShortOrigin = minimock.CallerInfo(1)
	return mmGetShort.mock
}

// When sets expectation for the LongShortRepository.GetShort which will trigger the result defined by the following
// Then helper
func (mmGetShort *mLongShortRepositoryMockGetShort) When(ctx context.Context, LongUrl *model.LongUrls) *LongShortRepositoryMockGetShortExpectation {
	if mmGetShort.mock.funcGetShort != nil {
		mmGetShort.mock.t.Fatalf("LongShortRepositoryMock.GetShort mock is already set by Set")
	}

	expectation := &LongShortRepositoryMockGetShortExpectation{
		mock:               mmGetShort.mock,
		params:             &LongShortRepositoryMockGetShortParams{ctx, LongUrl},
		expectationOrigins: LongShortRepositoryMockGetShortExpectationOrigins{origin: minimock.CallerInfo(1)},
	}
	mmGetShort.expectations = append(mmGetShort.expectations, expectation)
	return expectation
}

// Then sets up LongShortRepository.GetShort return parameters for the expectation previously defined by the When method
func (e *LongShortRepositoryMockGetShortExpectation) Then(up1 *model.UrlFullInfo, err error) *LongShortRepositoryMock {
	e.results = &LongShortRepositoryMockGetShortResults{up1, err}
	return e.mock
}

// Times sets number of times LongShortRepository.GetShort should be invoked
func (mmGetShort *mLongShortRepositoryMockGetShort) Times(n uint64) *mLongShortRepositoryMockGetShort {
	if n == 0 {
		mmGetShort.mock.t.Fatalf("Times of LongShortRepositoryMock.GetShort mock can not be zero")
	}
	mm_atomic.StoreUint64(&mmGetShort.expectedInvocations, n)
	mmGetShort.expectedInvocationsOrigin = minimock.CallerInfo(1)
	return mmGetShort
}

func (mmGetShort *mLongShortRepositoryMockGetShort) invocationsDone() bool {
	if len(mmGetShort.expectations) == 0 && mmGetShort.defaultExpectation == nil && mmGetShort.mock.funcGetShort == nil {
		return true
	}

	totalInvocations := mm_atomic.LoadUint64(&mmGetShort.mock.afterGetShortCounter)
	expectedInvocations := mm_atomic.LoadUint64(&mmGetShort.expectedInvocations)

	return totalInvocations > 0 && (expectedInvocations == 0 || expectedInvocations == totalInvocations)
}

// GetShort implements mm_repository.LongShortRepository
func (mmGetShort *LongShortRepositoryMock) GetShort(ctx context.Context, LongUrl *model.LongUrls) (up1 *model.UrlFullInfo, err error) {
	mm_atomic.AddUint64(&mmGetShort.beforeGetShortCounter, 1)
	defer mm_atomic.AddUint64(&mmGetShort.afterGetShortCounter, 1)

	mmGetShort.t.Helper()

	if mmGetShort.inspectFuncGetShort != nil {
		mmGetShort.inspectFuncGetShort(ctx, LongUrl)
	}

	mm_params := LongShortRepositoryMockGetShortParams{ctx, LongUrl}

	// Record call args
	mmGetShort.GetShortMock.mutex.Lock()
	mmGetShort.GetShortMock.callArgs = append(mmGetShort.GetShortMock.callArgs, &mm_params)
	mmGetShort.GetShortMock.mutex.Unlock()

	for _, e := range mmGetShort.GetShortMock.expectations {
		if minimock.Equal(*e.params, mm_params) {
			mm_atomic.AddUint64(&e.Counter, 1)
			return e.results.up1, e.results.err
		}
	}

	if mmGetShort.GetShortMock.defaultExpectation != nil {
		mm_atomic.AddUint64(&mmGetShort.GetShortMock.defaultExpectation.Counter, 1)
		mm_want := mmGetShort.GetShortMock.defaultExpectation.params
		mm_want_ptrs := mmGetShort.GetShortMock.defaultExpectation.paramPtrs

		mm_got := LongShortRepositoryMockGetShortParams{ctx, LongUrl}

		if mm_want_ptrs != nil {

			if mm_want_ptrs.ctx != nil && !minimock.Equal(*mm_want_ptrs.ctx, mm_got.ctx) {
				mmGetShort.t.Errorf("LongShortRepositoryMock.GetShort got unexpected parameter ctx, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetShort.GetShortMock.defaultExpectation.expectationOrigins.originCtx, *mm_want_ptrs.ctx, mm_got.ctx, minimock.Diff(*mm_want_ptrs.ctx, mm_got.ctx))
			}

			if mm_want_ptrs.LongUrl != nil && !minimock.Equal(*mm_want_ptrs.LongUrl, mm_got.LongUrl) {
				mmGetShort.t.Errorf("LongShortRepositoryMock.GetShort got unexpected parameter LongUrl, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
					mmGetShort.GetShortMock.defaultExpectation.expectationOrigins.originLongUrl, *mm_want_ptrs.LongUrl, mm_got.LongUrl, minimock.Diff(*mm_want_ptrs.LongUrl, mm_got.LongUrl))
			}

		} else if mm_want != nil && !minimock.Equal(*mm_want, mm_got) {
			mmGetShort.t.Errorf("LongShortRepositoryMock.GetShort got unexpected parameters, expected at\n%s:\nwant: %#v\n got: %#v%s\n",
				mmGetShort.GetShortMock.defaultExpectation.expectationOrigins.origin, *mm_want, mm_got, minimock.Diff(*mm_want, mm_got))
		}

		mm_results := mmGetShort.GetShortMock.defaultExpectation.results
		if mm_results == nil {
			mmGetShort.t.Fatal("No results are set for the LongShortRepositoryMock.GetShort")
		}
		return (*mm_results).up1, (*mm_results).err
	}
	if mmGetShort.funcGetShort != nil {
		return mmGetShort.funcGetShort(ctx, LongUrl)
	}
	mmGetShort.t.Fatalf("Unexpected call to LongShortRepositoryMock.GetShort. %v %v", ctx, LongUrl)
	return
}

// GetShortAfterCounter returns a count of finished LongShortRepositoryMock.GetShort invocations
func (mmGetShort *LongShortRepositoryMock) GetShortAfterCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetShort.afterGetShortCounter)
}

// GetShortBeforeCounter returns a count of LongShortRepositoryMock.GetShort invocations
func (mmGetShort *LongShortRepositoryMock) GetShortBeforeCounter() uint64 {
	return mm_atomic.LoadUint64(&mmGetShort.beforeGetShortCounter)
}

// Calls returns a list of arguments used in each call to LongShortRepositoryMock.GetShort.
// The list is in the same order as the calls were made (i.e. recent calls have a higher index)
func (mmGetShort *mLongShortRepositoryMockGetShort) Calls() []*LongShortRepositoryMockGetShortParams {
	mmGetShort.mutex.RLock()

	argCopy := make([]*LongShortRepositoryMockGetShortParams, len(mmGetShort.callArgs))
	copy(argCopy, mmGetShort.callArgs)

	mmGetShort.mutex.RUnlock()

	return argCopy
}

// MinimockGetShortDone returns true if the count of the GetShort invocations corresponds
// the number of defined expectations
func (m *LongShortRepositoryMock) MinimockGetShortDone() bool {
	if m.GetShortMock.optional {
		// Optional methods provide '0 or more' call count restriction.
		return true
	}

	for _, e := range m.GetShortMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			return false
		}
	}

	return m.GetShortMock.invocationsDone()
}

// MinimockGetShortInspect logs each unmet expectation
func (m *LongShortRepositoryMock) MinimockGetShortInspect() {
	for _, e := range m.GetShortMock.expectations {
		if mm_atomic.LoadUint64(&e.Counter) < 1 {
			m.t.Errorf("Expected call to LongShortRepositoryMock.GetShort at\n%s with params: %#v", e.expectationOrigins.origin, *e.params)
		}
	}

	afterGetShortCounter := mm_atomic.LoadUint64(&m.afterGetShortCounter)
	// if default expectation was set then invocations count should be greater than zero
	if m.GetShortMock.defaultExpectation != nil && afterGetShortCounter < 1 {
		if m.GetShortMock.defaultExpectation.params == nil {
			m.t.Errorf("Expected call to LongShortRepositoryMock.GetShort at\n%s", m.GetShortMock.defaultExpectation.returnOrigin)
		} else {
			m.t.Errorf("Expected call to LongShortRepositoryMock.GetShort at\n%s with params: %#v", m.GetShortMock.defaultExpectation.expectationOrigins.origin, *m.GetShortMock.defaultExpectation.params)
		}
	}
	// if func was set then invocations count should be greater than zero
	if m.funcGetShort != nil && afterGetShortCounter < 1 {
		m.t.Errorf("Expected call to LongShortRepositoryMock.GetShort at\n%s", m.funcGetShortOrigin)
	}

	if !m.GetShortMock.invocationsDone() && afterGetShortCounter > 0 {
		m.t.Errorf("Expected %d calls to LongShortRepositoryMock.GetShort at\n%s but found %d calls",
			mm_atomic.LoadUint64(&m.GetShortMock.expectedInvocations), m.GetShortMock.expectedInvocationsOrigin, afterGetShortCounter)
	}
}

// MinimockFinish checks that all mocked methods have been called the expected number of times
func (m *LongShortRepositoryMock) MinimockFinish() {
	m.finishOnce.Do(func() {
		if !m.minimockDone() {
			m.MinimockCreateNewURLInspect()

			m.MinimockGetLongInspect()

			m.MinimockGetShortInspect()
		}
	})
}

// MinimockWait waits for all mocked methods to be called the expected number of times
func (m *LongShortRepositoryMock) MinimockWait(timeout mm_time.Duration) {
	timeoutCh := mm_time.After(timeout)
	for {
		if m.minimockDone() {
			return
		}
		select {
		case <-timeoutCh:
			m.MinimockFinish()
			return
		case <-mm_time.After(10 * mm_time.Millisecond):
		}
	}
}

func (m *LongShortRepositoryMock) minimockDone() bool {
	done := true
	return done &&
		m.MinimockCreateNewURLDone() &&
		m.MinimockGetLongDone() &&
		m.MinimockGetShortDone()
}
